spring:
  application:
    name: school-management-system
  
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: false

server:
  port: ${PORT:80}
  address: 0.0.0.0

logging:
  level:
    root: WARN
    com.school: INFO
